# https://developers.cloudflare.com/workers/wrangler/configuration/

compatibility_date = "2024-01-01"
workers_dev = false

# main = "playground/cloudflare.ts"
main = "playground/cloudflare-durable.ts"

[[durable_objects.bindings]]
name = "$DurableObject"
class_name = "$DurableObject"

[[migrations]]
tag = "v1"
new_classes = ["$DurableObject"]
