name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Update Corepack
        run: npm i --global corepack@latest
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test:types
      - run: pnpm build
      - run: pnpm vitest run --coverage
      - uses: codecov/codecov-action@v5
